POST http://localhost:3003/api/blogs/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFzZGYiLCJpZCI6IjY5ZDdiOTNlYmQyNmJmMDRkNjIxZWU0YyIsImlhdCI6MTc3NTc0NjY5MX0.3L2OxR33sTatL1mlJkuueNp5dCCGKxrwVUdOejmwZyQ

{
  "title": "mmm title",
  "author": "mmm author",
  "url": "http://mmmmm.test",
  "likes": ""
}